services:
    kns_utils_staging:
        environment:
            ADMINER_DEFAULT_SERVER: host.containers.internal:5433
            ADMINER_DESIGN: hever
        extra_hosts:
            - host.containers.internal:host-gateway
        image: adminer
        ports:
            - 8081:8080
        restart: unless-stopped
        volumes:
            - ./plugins-enabled:/var/www/html/plugins-enabled:ro
