package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"golang.org/x/sync/errgroup"
	"gopkg.in/yaml.v3"
)

// runOrchestrator is the main entry point for the application logic.
//
// It performs the following steps:
//
// 1. Checks for external prerequisites (compose tool, tsh, socat).
//
// 2. Loads and validates the selected database configurations from the settings file.
//
// 3. Generates a compose file with services for each selected database.
//
// 4. Brings up the compose services.
//
// 5. For each database, starts a proxy tunnel and a socat forwarder in separate goroutines.
//
// 6. Waits for all goroutines to complete, returning any errors that occur.
func runOrchestrator(ctx context.Context, configPath string, selectedNames []string, outputDir string) (err error) {
	// Verify external prerequisites first
	if err := CheckPrerequisites(); err != nil {
		return err
	}

	selected, err := LoadSelectedDatabases(configPath, selectedNames)
	if err != nil {
		return err
	}

	composeBase, err := detectComposeCmd()
	if err != nil {
		return fmt.Errorf("failed to detect compose command: %w", err)
	}

	// Clear output directory before starting.
	err = os.RemoveAll(outputDir)
	if err != nil {
		return fmt.Errorf("failed to clear output dir: %w", err)
	}
	err = os.MkdirAll(outputDir, 0755)
	if err != nil {
		return fmt.Errorf("failed to create output dir: %w", err)
	}

	// Generate the compose file with a service for each selected database.
	// Each service is generated by Database.ToComposeService() which returns a YAML-compatible
	// map with the necessary configuration to run Adminer connected to the database's
	// socat forwarder. We marshal the entire compose data to YAML and write it to disk.
	services := make(map[string]any)
	for _, db := range selected {
		services[db.ServiceName()] = db.ToComposeService()
	}
	composeData, err := yaml.Marshal(map[string]any{"services": services})
	if err != nil {
		return fmt.Errorf("failed to marshal compose data: %w", err)
	}
	err = os.WriteFile(ComposeFile, composeData, 0644)
	if err != nil {
		return fmt.Errorf("failed to write compose file: %w", err)
	}

	fmt.Printf("🚀 Starting Adminer via %s...\n", strings.Join(composeBase, " "))

	// Bring up the compose services. We defer bringing them down so that if any error occurs
	// later on, we still attempt to clean up the compose services. Note that if composeUpCmd
	// fails, we return immediately and the deferred composeDownCmd is a no-op since the
	// services never started.
	if err := composeUpCmd(composeBase, ComposeFile); err != nil {
		return err
	}
	defer func() {
		fmt.Println("🛑 Cleaning up...")
		err = composeDownCmd(composeBase, ComposeFile)
		if err != nil {
			fmt.Printf("❌ Failed to bring down compose services: %v\n", err)
		}
	}()

	// Create a cancellable child context used by all worker goroutines.
	// Calling cancelGroup() cancels childCtx and signals all workers
	// (proxy tunnels and socat processes) to stop. We defer it so that
	// when runOrchestrator returns (normal exit or error) all external
	// processes are asked to terminate and logs/cleanup can run.
	childCtx, cancelGroup := context.WithCancel(ctx)
	defer cancelGroup()

	// Create an errgroup that derives from the child context. The group's
	// groupCtx is cancelled when any goroutine returns a non-nil error.
	// Note: each goroutine below also calls cancelGroup() when it exits
	// (deferred inside the goroutine). That means if any single process
	// (tunnel or socat) stops — whether due to an error or normal exit —
	// we cancel the shared context and the entire application stops the
	// remaining processes. This implements the behavior: when one of the
	// processes stops, the whole app will be stopped. It also ensures
	// that when the app is stopped, all tunnels and socat instances are
	// killed.
	g, groupCtx := errgroup.WithContext(childCtx)

	// Spawn a pair of goroutines for each database: one for the proxy tunnel
	// and one for the socat forwarder. Both are cancelled if either fails.
	for _, db := range selected {

		// Each goroutine runs the corresponding Database method which executes the external command
		// to start the process and waits for it to complete. If the process exits with an error,
		// we log the error and the path to the log file, and return the error which triggers
		// cancellation of all processes via the shared context.
		g.Go(func() error {
			defer cancelGroup()
			err := db.RunProxyTunnel(groupCtx, outputDir)
			if err != nil {
				fmt.Printf("❌ [%s] TSH error: %v\n", db.Name, err)
				fmt.Printf("   Check %s for details\n", db.ProxyTunnelLogPath())
			}
			return err
		})

		// We print the Adminer URL before starting the socat process since the URL is valid as soon as the proxy tunnel is up,
		// and the socat process is just forwarding traffic to that tunnel.
		// This way if the socat process fails to start, the user still has the correct URL to troubleshoot with
		// (e.g. by trying to connect with Adminer or another client).
		g.Go(func() error {
			defer cancelGroup()
			fmt.Printf("🔗 [%s] -> %s\n", db.Name, db.AdminerURL())
			err := db.RunSocat(groupCtx, outputDir)
			if err != nil {
				fmt.Printf("❌ [%s] SOCAT error: %v\n", db.Name, err)
				fmt.Printf("   Check %s for details\n", db.SocatLogPath())
			}
			return err
		})
	}

	// Wait for all goroutines to complete. If any returns an error,
	// g.Wait() returns immediately and the deferred cancelGroup() above
	// ensures all other processes are stopped.
	err = g.Wait()
	if err != nil {
		return err
	}

	return nil
}
